### ISSUE TITLE
A better implementation of the isRequired function of FormWrapperComponent

### ISSUE THREAD

**Issue by asiewe** [IsyFact/isy-angular-widgets#224]
Currently, the function isRequired checks if validationMessage has a property required to mark a field as required. This approach is flawed and causes a bug in our application: we set the validationMessages dynamically based on the formControl error object. For required fields, the error object has a required field only when the field is empty, causing isRequired to return false and the field not to be marked as required.

A better implementation should be based on the formControl rather than the validationMessage.

```ts
/**
* Computes and returns the information about the required state
* @returns the required state
*/
isRequired(): boolean {
  return this.control.hasValidator(Validators.required)
}

```

**Comment by Aspern** [comment]
Thank you for reporting your problem, we are planning a fix for the upcoming minor release.
