### ISSUE TITLE
Enter Key Triggering CharPicker in Forms

### ISSUE THREAD

**Issue by asiewe** [IsyFact/isy-angular-widgets#229]
When pressing "Enter" in any field within a form, the `isyInputChar` directive causes the CharPicker to appear. This behavior occurs when the `isyInputChar` directive is applied to an element within a form.

#### Steps to Reproduce:
This issue can be reproduced in the demo application available on the following page: [https://isyfact.github.io/isy-angular-widgets/objekt-anzeigen/42](https://isyfact.github.io/isy-angular-widgets/objekt-anzeigen/42)

#### Proposed Solution:
Replace the `pButton` directive with the `p-button` component in `input-char.component.html` to avoid the unintended behavior.

**Comment by msg-jstren** [comment]
Thank you for reporting your problem, we are planning a fix to be implemented in release 18.2.x.
